export const basePlayers = [
  "Charles Niedringhaus",
  "Holly Milnes",
  "Tara Gartland",
  "Jennifer Reshetar",
  "Mike Duarte",
  "Shelby Montes De Oca",
  "Carter Knight",
  "Katrina Siske",
  "Sara Meixner",
  "Joe Ogletree",
  "Jack Amsterdam",
  "Myles Hohman",
  "Snow Vongsakulvong",
  "Phillip Ramirez",
  "Pieter Vandenburg",
  "Lori Tusiano",
  "Connor Parahus",
  "Sabrina McGarrity",
  "Christopher Munden",
  "Kaylee Richard",
  "Vince Suriani",
  "Jaden Surratte",
  "Brian Corchiolo",
  "Kristen Sands",
  "Reeba Ivan",
  "Justina Akpali",
  "Alyssa Piselli",
  "Cheyenne Scott",
  "Christine Robinson",
  "Aaron Cocks",
  "Jen Barthelemy",
  "Pam Jackson",
  "Sean Gibbons",
  "Gaston Soto",
  "Francesca DiPlacido",
  "Sean Fuchs",
];

export const giftsData = [
  { id: 1, name: "Bird Gang Towel", link: "https://www.amazon.com/dp/B0F6V5S7VJ/?coliid=I19MLAHFMESZHX&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_6DGY6H9AYA9HKXE3C95G", imageFile: "gift1.jpg" },
  { id: 2, name: "Mini Waffle Maker", link: "https://www.amazon.com/dp/B01M9I779L/?coliid=I1DGT2J5TAMQND&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_QWE7Z4BWNRYG4XY5JDGR", imageFile: "gift2.jpg" },
  { id: 3, name: "Cable Organizer", link: "https://www.amazon.com/dp/B0924H4XB9/?coliid=I191L5P114QTV5&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_8A94KQGGMBVED94CQTTF_1", imageFile: "gift3.jpg" },
  { id: 4, name: "Electric Hand Warmers", link: "https://www.amazon.com/dp/B0CHFDWF3L/?coliid=I2BXFGEUVUI8Q8&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_1Z7S0V8JSZJBHRM3RNDT", imageFile: "gift4.jpg" },
  { id: 5, name: "Dumpster Fire Socks", link: "https://www.amazon.com/GOLIN-Dumpster-Positive-Birthday-Christmas/dp/B0G2LFDM5K/ref=sr_1_19?crid=3V842HFWG14B7&dib=eyJ2IjoiMSJ9.ytKbU-RWx5VIeC3eGXot4cXFPCCngVJ7uiAUi1n6p7ztnUAvPCNJ-HytMdBrU2XNaohpMXbFmUmFYF0Wi0EO8AyMRBDY7jl-Qhc1zNabxAMO_dZLpCm3llYXneY3QoHpq754Vv4b8VA91fAV1_Oj0sAHceQtPoqX2-DOdbm9CoZk8go00WVEimJc41Hvy8h_HKixMzFNbCTugd44yETrLTeIHncsS1IpqZNJiJLt5KXOcUb6ALxzRgq_Eq7EKdOvdWRsNTxBXJekJd8KuuoAGwHQCqqAC-bxKB1RQw4ASpo.JCzQAU8phYwk8F3FuQ55f4LNPQQes9Zgo42btImsr30&dib_tag=se&keywords=dumpster+fire+socks&qid=1765294748&sprefix=dumpster+fire+socks%2Caps%2C108&sr=8-19", imageFile: "gift5.jpg" },
  { id: 6, name: "Multi-Port Charging Cords", link: "https://www.amazon.com/dp/B0DP8SDB1Z/?coliid=I2PUZNPQXBS012&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_BZS5NNRX8HXJ62WFD2HK", imageFile: "gift6.jpg" },
  { id: 7, name: "Popcorn Maker", link: "https://www.amazon.com/dp/B07NWCTXHH/?coliid=I13A08CG71VNEG&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_B477RHHW9R0JRK7NHYSE", imageFile: "gift7.jpg" },
  { id: 8, name: "Car Cleaning Putty", link: "https://www.amazon.com/dp/B081T7N948/?coliid=I2V4SXORNGOFN4&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_RB63HGQGTADHHR8DZTVQ", imageFile: "gift8.jpg" },
  { id: 9, name: "Silicone Spatula Set", link: "https://www.amazon.com/dp/B0CHGFG64S/?coliid=IXDAFORNA3A6D&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_FQTARKMP3SEZ3J13AXS2", imageFile: "gift9.jpg" },
  { id: 10, name: "Nee Doh Stress Ball", link: "https://www.amazon.com/dp/B0D9ZTW7PS/?coliid=I2TST8KEV6AHUF&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_DGBVZS31E26V8A3VK0CW", imageFile: "gift10.jpg" },
  { id: 11, name: "Glass Straws", link: "https://www.amazon.com/dp/B0BW8F9LG8/?coliid=I2QHPEFJ9SNFRT&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_33F0ZZFK31EG5K9R0RDC", imageFile: "gift11.jpg" },
  { id: 12, name: "Cable Ties", link: "https://www.amazon.com/dp/B0CT39QKWL/?coliid=IYO6AWKZ5B937&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_QHJQRAFWSFRVSENG6RRB", imageFile: "gift12.jpg" },
  { id: 13, name: "$10 Amazon Gift Card", link: "https://www.amazon.com/dp/B0DCZLNX94/?coliid=ICPDIO3Q0S1KZ&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_7BSSA5ER1165JJJE7149", imageFile: "gift13.jpg" },
  { id: 14, name: "Poo-Pourri", link: "https://www.amazon.com/dp/B0CRQQ8TYB/?coliid=I2E3DPWKJAB82Y&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_2P2W45VBDCH0BCKPXT3R", imageFile: "gift14.jpg" },
  { id: 15, name: "Glass Food Containers", link: "https://www.amazon.com/dp/B0DWLHPM8Q/?coliid=IYJF5G2OVXXG8&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_18S1P07A9MH4FTKPDZ2P", imageFile: "gift15.jpg" },
  { id: 16, name: "Travel Medicine Organizer", link: "https://www.amazon.com/dp/B0D9LW5VCM/?coliid=I3QDOUHIOK5IMX&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_SH029WNZCQ0KTWREKPQ6", imageFile: "gift16.jpg" },
  { id: 17, name: "Emotional Support Dumpster Fire", link: "https://www.amazon.com/dp/B0F48FDXRN/?coliid=I1G6PM71EVYM6P&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_70Y30CPJSG8GJNEPB70T", imageFile: "gift17.jpg" },
  { id: 18, name: "Travel Salad Container", link: "https://www.amazon.com/dp/B0B247R9XB/?coliid=I2LLFF9DTCA219&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_HQCAV7199WQYNXM1A0FQ", imageFile: "gift18.jpg" },
  { id: 19, name: "Silicone Pot Holders", link: "https://www.amazon.com/dp/B08J8H7BQG/?coliid=I3OO0H3ECAD2YO&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_J4VDTNCVQZZMX76WZ96F", imageFile: "gift19.jpg" },
  { id: 20, name: "Candle", link: "https://www.amazon.com/dp/B075KTPM84/?coliid=I1GFTLY435AXSK&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_V45TSDNXFSPKB202DWS1", imageFile: "gift20.jpg" },
  { id: 21, name: "Rotatable Cord Holders", link: "https://www.amazon.com/dp/B0FR4YCH36/?coliid=I2RMROSM6TUSRI&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_QHYPFP24W94BG7YAX651", imageFile: "gift21.jpg" },
  { id: 22, name: "P is For Pizza", link: "https://www.amazon.com/dp/B0CFW3CY7B/?coliid=I2C4RZG772BP34&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_E34YK416RP7WX6K0W6SJ", imageFile: "gift22.jpg" },
  { id: 23, name: "Magic Stain Remover", link: "https://www.amazon.com/dp/B01EIG6A4Q/?coliid=I53S4MAKFHLSY&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_9YJBT5ZV5BS2D3XFYXBN", imageFile: "gift23.jpg" },
  { id: 24, name: "Portable Charger", link: "https://www.amazon.com/dp/B0FHQ9LPF2/?coliid=I3JIN7S9LNKO1Y&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_599MQMZYAGP70CDJGCY9", imageFile: "gift24.jpg" },
  { id: 25, name: "Nerds Gummy Clusters", link: "https://www.amazon.com/dp/B09M1NZ92V/?coliid=I5CGEP75B9E0H&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_599MQMZYAGP70CDJGCY9_1", imageFile: "gift25.jpg" },
  { id: 26, name: "Electric Salt & Pepper Grinder", link: "https://www.amazon.com/dp/B0DQZLZ7Y6/?coliid=I1UXZYAEJ799A8&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_RH422STXNJFPJEM6TXMA", imageFile: "gift26.jpg" },
  { id: 27, name: "Luggage Scale", link: "https://www.amazon.com/dp/B07QFTGGYF/?coliid=ISERWYIDSNY7X&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_RQVNW2BWY3J5F91FXQJK", imageFile: "gift27.jpg" },
  { id: 28, name: "Aquaphor", link: "https://www.amazon.com/dp/B004FHZKOA/?coliid=I3Q0KJ8CCMAARN&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_SB8N6P7YA6QYE19TA0YV", imageFile: "gift28.jpg" },
  { id: 29, name: "Travel Utensils Set", link: "https://www.amazon.com/dp/B0CGV49V6C/?coliid=I27UCOK5GK3SGE&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_5HS1V7BZDWXFTX9NV89A", imageFile: "gift29.jpg" },
  { id: 30, name: "Mug Warmer", link: "https://www.amazon.com/dp/B0CCTPNZD4/?coliid=I222HG4YZ07BUH&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_CTXQMN47XAW7A2KVN06B", imageFile: "gift30.jpg" },
  { id: 31, name: "Daily Dad Jokes Calendar", link: "https://www.amazon.com/dp/B0F99SN3D8/?coliid=I2KBXJOOBBSOYX&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_8SWY6FWWBF7KTQ4KF0PE", imageFile: "gift31.jpg" },
  { id: 32, name: "Car Air Fresheners", link: "https://www.amazon.com/dp/B0F5M7K5GT/?coliid=I17Q53UI7CNN56&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_N2PTN1ZSFX2QDP5E91RJ", imageFile: "gift32.jpg" },
  { id: 33, name: "Phone Stand", link: "https://www.amazon.com/dp/B0949DWJCV/?coliid=I1R78F9GZMFHPR&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_31BKNFEZK2MY066Y6N6X", imageFile: "gift33.jpg" },
  { id: 34, name: "Desk Pad", link: "https://www.amazon.com/dp/B07JW4ZJ3M/?coliid=I38V3CX4NF6BA1&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_6AWN7KW1TRXMW1GEK4BV", imageFile: "gift34.jpg" },
  { id: 35, name: "Extendable Back Scratcher", link: "https://www.amazon.com/dp/B07VV31KN2/?coliid=I3V055C09IILYI&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_029CG69VE0PWYQ6KYS2D", imageFile: "gift35.jpg" },
  { id: 36, name: "Digital Meat Thermometer", link: "https://www.amazon.com/dp/B0F5X4FM3Q/?coliid=I23FK00ZSA1W3B&colid=3VKDCDCM980UY&psc=1&ref_=cm_sw_r_cp_ud_lstpd_6RNA6WWXC7WVYRE9GF8Y", imageFile: "gift36.jpg" },
];

export const totalGifts = giftsData.length;
